#include "core/Localization.h"

#include <algorithm>
#include <cctype>
#include <mutex>
#include <string_view>
#include <unordered_map>

namespace neuracoust::daw {
namespace {

UiLanguage gLanguage = UiLanguage::English;
std::mutex gLanguageMutex;

std::string normalizeLocaleTag(std::string tag) {
    std::replace(tag.begin(), tag.end(), '_', '-');
    std::transform(tag.begin(), tag.end(), tag.begin(), [](unsigned char ch) {
        return static_cast<char>(std::tolower(ch));
    });
    return tag;
}

using Table = std::unordered_map<std::string_view, std::string_view>;

const Table& englishStrings() {
    static const Table strings = {
        {"common.close", "Close"},
        {"ai.title", "AI Assistant"},
        {"ai.project.untitled", "Untitled"},
        {"ai.summary", "Project {project} · {tracks} tracks · {audio} audio · {clips} clips · {bpm} bpm"},
        {"ai.safe_mode", "Safe Mode {state} · Local AI: {decision} · {message}"},
        {"ai.state.idle", "Idle"},
        {"ai.state.playback", "Playback"},
        {"ai.state.recording", "Recording"},
        {"ai.decision.allow_now", "allow now"},
        {"ai.decision.queue_until_idle", "queue until idle"},
        {"ai.decision.block", "blocked"},
        {"ai.guard.allowed", "Local AI is allowed under the current DAW safety policy."},
        {"ai.guard.recording", "Recording is active; defer local AI to protect realtime capture."},
        {"ai.guard.transport", "Transport is running; queue non-light local AI until playback stops."},
        {"ai.guard.disabled", "Local AI is disabled; keep DAW features available without assistant inference."},
        {"ai.guard.resource_pressure", "High resource pressure detected; block local AI inference for now."},
        {"ai.selected_clip", "Selected clip: {clip} · track {track}"},
        {"ai.selected_clip.none", "Selected clip: none · project-level assistant context only"},
        {"ai.audio.summary", "Audio: {duration}s · {channels} ch · {sampleRate} Hz · peak {peak} · RMS {rms} · crest {crest} · centroid {centroid} Hz"},
        {"ai.audio.large", "Audio: large file skipped in UI; queue offline analysis instead."},
        {"ai.audio.offline", "Audio: offline analysis recommended ({reason})"},
        {"ai.role", "Role: {role}"},
        {"ai.chain", "Chain: "},
        {"ai.why", "Why: {reason}"},
        {"ai.diagnostics", "Diagnostics:"},
        {"ai.edit_suggestions", "Edit suggestions:"},
        {"ai.external_jobs_ready", "External jobs ready:"},
        {"ai.idea_generator", "Idea generator: {engine} / {mode}"},
        {"ai.prompt.default", "Look at the vocal/mix state and suggest one safe JSON command preview."},
        {"ai.context.clip", "Current target: selected clip {clip} · track {track} · listening path: clip source / track output candidate"},
        {"ai.context.track", "Current target: selected track/channel {track} · listening path: track output"},
        {"ai.context.master", "Current target: selected master channel {track} · listening path: master output"},
        {"ai.context.mix", "Current target: full mix · listening path: master output"},
        {"ai.scope.clip", "For the selected clip {clip} on track {track},"},
        {"ai.scope.track", "For the selected track/channel {track},"},
        {"ai.scope.master", "For the selected master/full mix,"},
        {"ai.scope.mix", "For the current project's full mix,"},
        {"ai.quick.diagnose", "Mix Check"},
        {"ai.quick.chain", "Chain"},
        {"ai.quick.clip", "Clip"},
        {"ai.quick.record", "Record Coach"},
        {"ai.prompt.diagnose", "{scope} diagnose level, headroom, spectral balance, masking, and dynamics issues, then suggest one safe JSON command preview."},
        {"ai.prompt.chain", "{scope} recommend an insert/send chain for the current sound role, and suggest only one safe JSON command preview if a direct change is safe."},
        {"ai.prompt.clip", "{scope} analyze source type, noise, clipping, silence, and edit points, then suggest any needed offline analysis jobs."},
        {"ai.prompt.record", "{scope} briefly coach the next recording or retake: input level, noise, monitoring, and headroom."},
        {"ai.status.quick_prompt", "Request preset inserted · edit the text if needed, then choose Run or Ollama"},
        {"ai.prompt.placeholder", "Ask for lyrics, stem analysis, mix advice, or a safe edit..."},
        {"ai.prompt.tooltip", "Optional instruction. The default Run button uses local analysis first; Ollama is optional."},
        {"ai.run_primary", "Run"},
        {"ai.run_primary.tooltip", "Queue the selected local AI analysis using Apple Neural Engine/Core ML on Apple Silicon when available."},
        {"ai.ask_ollama", "Ask Ollama"},
        {"ai.ask_ollama.tooltip", "Send the typed request to the local Ollama sidecar."},
        {"ai.engine.primary", "Engine: Apple Neural Engine/Core ML first · GPU on Windows · Ollama optional"},
        {"ai.engine.badges", "Default local engine: ANE/Core ML · GPU · optional Ollama"},
        {"ai.prepared_jobs", "Ready jobs:"},
        {"ai.workflow.clip", "Workflow: Stem separation -> lyric transcription -> tags/search can be queued for this clip."},
        {"ai.workflow.track", "Workflow: track analysis, transcription, and embedding jobs are ready for this channel."},
        {"ai.workflow.mix", "Workflow: full mix diagnostic and embedding jobs are ready."},
        {"ai.button.stem_magic", "StemMagic"},
        {"ai.button.stage_chain", "Stage Chain"},
        {"ai.button.apply", "Apply"},
        {"ai.button.reject", "Reject"},
        {"ai.button.save_memory", "Save Memory"},
        {"ai.button.queue", "Queue"},
        {"ai.button.snapshot", "Snapshot"},
        {"ai.button.show_report", "Details"},
        {"ai.button.show_report.tooltip", "Show the technical AI report only when needed."},
        {"ai.button.copy_report", "Copy Report"},
        {"ai.button.copy_report.tooltip", "Copy the detailed AI report to the clipboard."},
        {"ai.status.ready", "Ready · local analysis is queued only when you run it"},
        {"ai.status.report_visible", "Detailed report visible"},
        {"ai.no_report.body", "No detailed AI report is available yet."},
        {"ai.status.request_sent", "Ollama request sent..."},
        {"ai.status.unavailable", "Ollama unavailable"},
        {"ai.status.parse_failed", "Ollama response parse failed"},
        {"ai.status.response_ready_preview", "AI response ready · preview detected"},
        {"ai.status.response_ready", "AI response ready"},
        {"ai.status.no_preview", "No AI command preview to apply"},
        {"ai.status.preview_rejected", "Preview rejected"},
        {"ai.status.unsupported_preview", "Preview not directly applicable"},
        {"ai.status.no_change", "No change applied"},
        {"ai.status.preview_applied", "AI preview applied"},
        {"ai.status.preview_rejected_user", "AI preview rejected"},
        {"ai.status.memory_failed", "AI memory save failed"},
        {"ai.status.memory_saved", "AI memory saved"},
        {"ai.status.no_external_jobs", "No external AI jobs ready"},
        {"ai.status.external_queue_staged", "External AI queue staged"},
        {"ai.status.no_chain", "No chain suggestion to stage"},
        {"ai.status.chain_not_staged", "Chain not staged"},
        {"ai.status.chain_staged", "AI chain staged"},
        {"ai.report_copied", "AI report copied"},
        {"ai.snapshot_copied", "AI snapshot copied"},
        {"ai.no_content", "No content"},
        {"ai.invalid_preview_json", "Invalid preview JSON"},
        {"ai.unsupported_preview.body", "This preview is queued as an external or unsupported AI action."},
        {"ai.no_change.body", "The AI command was valid but did not change the project."},
        {"ai.applied_preview.body", "Applied AI preview:\n{json}"},
        {"ai.saved_memory.body", "Saved AI mix memory:\n{path}"},
        {"ai.external_queue.body", "External AI jobs queued as sidecar requests:\n"},
        {"ai.external_queue.item", "- {engine} / {mode}\n  input: {input}\n  out: {output}\n"},
        {"ai.chain.editable_only", "The suggested chain can only be staged on an editable audio/instrument/aux track."},
        {"ai.chain.no_slots", "No insert slots were added."},
        {"ai.chain.staged.body", "Staged {count} empty insert slots for AI chain on {track}.\nSuggested processors remain review notes, not auto-loaded plugins."},
        {"ai.role.vocal", "vocal"},
        {"ai.role.drums", "drums"},
        {"ai.role.bass", "bass"},
        {"ai.role.guitar", "guitar"},
        {"ai.role.keys", "keys"},
        {"ai.role.cleanup", "cleanup"},
        {"ai.role.general", "general"},
        {"ai.severity.info", "info"},
        {"ai.severity.warning", "warning"},
        {"ai.severity.critical", "critical"},
        {"ai.processor.gain_trim", "Gain trim"},
        {"ai.processor.subtractive_eq", "Subtractive EQ"},
        {"ai.processor.compressor", "Compressor"},
        {"ai.processor.ambience_send", "Ambience send"},
        {"ai.processor.de_esser", "De-esser"},
        {"ai.processor.saturation", "Saturation"},
        {"ai.processor.reverb_send", "Reverb send"},
        {"ai.processor.transient_shaper", "Transient shaper"},
        {"ai.processor.bus_compressor", "Bus compressor"},
        {"ai.processor.parallel_compression_send", "Parallel compression send"},
        {"ai.processor.low_cleanup_eq", "Low cleanup EQ"},
        {"ai.processor.sidechain_candidate", "Sidechain candidate"},
        {"ai.processor.high_pass_eq", "High-pass EQ"},
        {"ai.processor.tone_eq", "Tone EQ"},
        {"ai.processor.room_send", "Room send"},
        {"ai.processor.stereo_width_check", "Stereo width check"},
        {"ai.processor.gentle_compressor", "Gentle compressor"},
        {"ai.processor.delay_or_reverb_send", "Delay or reverb send"},
        {"ai.processor.noise_reduction_candidate", "Noise reduction candidate"},
        {"ai.processor.manual_edit_review", "Manual edit review"},
        {"ai.processor.clip_repair_review", "Clip repair or re-record review"},
        {"ai.processor.normalize_or_clip_gain", "Normalize or clip gain"},
        {"ai.rationale.general", "A conservative general chain keeps AI changes reviewable."},
        {"ai.rationale.vocal", "Vocal chains usually need cleanup, dynamics, presence, and a controlled space send."},
        {"ai.rationale.drums", "Drum tracks benefit from transient control and parallel density."},
        {"ai.rationale.bass", "Bass chains should stabilize low end and expose harmonics on small speakers."},
        {"ai.rationale.guitar", "Guitar chains usually need range control and contextual space."},
        {"ai.rationale.keys", "Keys often need space and width management more than heavy dynamics."},
        {"ai.rationale.cleanup", "Cleanup material should be repaired before musical processing."},
        // Help-mode tooltips (shown while the ? help toggle is on).
        {"help.split", "Split the clip at the cursor (B)"},
        {"help.heal", "Heal split clips (H)"},
        {"help.delete", "Delete the selection"},
        {"help.copy", "Copy"},
        {"help.cut", "Cut"},
        {"help.paste", "Paste"},
        {"help.duplicate", "Duplicate"},
        {"help.marker", "Add a marker at the playhead (Cmd+M)"},
        {"help.add_audio", "Add an audio track"},
        {"help.add_instrument", "Add an instrument track"},
        {"help.delete_track", "Delete the track"},
        {"help.range", "Range edits (cut / clear / insert)"},
        {"help.zoom_in", "Zoom in"},
        {"help.zoom_out", "Zoom out"},
        {"help.zoom_fit", "Fit to window"},
        {"help.grid", "Grid resolution (snap unit)"},
        {"help.mixer_io", "Show input/output (I/O) routing"},
        {"help.mixer_inserts", "Show insert slots"},
        {"help.mixer_sends", "Show sends"},
        {"help.mixer_memo", "Show the channel memo"},
        {"help.pan_law", "Mono-track pan law (project setting)"},
        {"help.automation_mode", "Cycle automation mode (Read -> Touch -> Latch -> Write -> Off)"},
        {"help.channel_wide", "Widen the channel"},
        {"help.channel_narrow", "Narrow the channel"},
        {"help.mode_on", "Help mode: hover any control to see what it does"},
        {"help.mode_off", "Turn help mode off"},
    };
    return strings;
}

const Table& koreanStrings() {
    static const Table strings = {
        {"common.close", "닫기"},
        {"ai.title", "AI 어시스턴트"},
        {"ai.project.untitled", "무제"},
        {"ai.summary", "프로젝트 {project} · 트랙 {tracks}개 · 오디오 {audio}개 · 클립 {clips}개 · {bpm} bpm"},
        {"ai.safe_mode", "안전 모드 {state} · 로컬 AI: {decision} · {message}"},
        {"ai.state.idle", "대기"},
        {"ai.state.playback", "재생 중"},
        {"ai.state.recording", "녹음 중"},
        {"ai.decision.allow_now", "바로 가능"},
        {"ai.decision.queue_until_idle", "대기 후 실행"},
        {"ai.decision.block", "차단"},
        {"ai.guard.allowed", "현재 DAW 안전 정책상 로컬 AI를 사용할 수 있습니다."},
        {"ai.guard.recording", "녹음 중이므로 실시간 캡처 보호를 위해 로컬 AI를 나중에 실행합니다."},
        {"ai.guard.transport", "재생 중이므로 가벼운 작업이 아닌 로컬 AI는 정지 후 실행합니다."},
        {"ai.guard.disabled", "로컬 AI가 꺼져 있어 추론 없이 DAW 기능만 유지합니다."},
        {"ai.guard.resource_pressure", "시스템 자원 사용량이 높아 현재 로컬 AI 추론을 막습니다."},
        {"ai.selected_clip", "선택 클립: {clip} · 트랙 {track}"},
        {"ai.selected_clip.none", "선택 클립: 없음 · 프로젝트 전체 기준으로만 분석합니다"},
        {"ai.audio.summary", "오디오: {duration}초 · {channels} ch · {sampleRate} Hz · 피크 {peak} · RMS {rms} · 크레스트 {crest} · 중심 주파수 {centroid} Hz"},
        {"ai.audio.large", "오디오: 큰 파일이라 패널 분석은 건너뜁니다. 오프라인 분석 작업으로 보내세요."},
        {"ai.audio.offline", "오디오: 오프라인 분석을 권장합니다 ({reason})"},
        {"ai.role", "역할: {role}"},
        {"ai.chain", "추천 체인: "},
        {"ai.why", "이유: {reason}"},
        {"ai.diagnostics", "진단:"},
        {"ai.edit_suggestions", "편집 제안:"},
        {"ai.external_jobs_ready", "준비된 외부 작업:"},
        {"ai.idea_generator", "아이디어 생성: {engine} / {mode}"},
        {"ai.prompt.default", "보컬/믹스 상태를 보고 안전한 JSON 명령 미리보기를 하나 제안해줘."},
        {"ai.context.clip", "현재 대상: 선택 클립 {clip} · 트랙 {track} · 듣는 경로: 클립 원본/트랙 출력 후보"},
        {"ai.context.track", "현재 대상: 선택 트랙/채널 {track} · 듣는 경로: 트랙 출력"},
        {"ai.context.master", "현재 대상: 선택 마스터 채널 {track} · 듣는 경로: 마스터 출력"},
        {"ai.context.mix", "현재 대상: 전체 믹스 · 듣는 경로: 마스터 출력"},
        {"ai.scope.clip", "현재 선택된 클립 {clip}, 이 클립이 속한 트랙 {track} 기준으로"},
        {"ai.scope.track", "현재 선택된 트랙/채널 {track} 기준으로"},
        {"ai.scope.master", "현재 선택된 마스터/전체 믹스 기준으로"},
        {"ai.scope.mix", "현재 프로젝트의 전체 믹스 기준으로"},
        {"ai.quick.diagnose", "믹스 진단"},
        {"ai.quick.chain", "체인 추천"},
        {"ai.quick.clip", "클립 분석"},
        {"ai.quick.record", "녹음 코치"},
        {"ai.prompt.diagnose", "{scope} 레벨, 헤드룸, 대역 밸런스, 마스킹, 다이내믹 문제를 진단하고 안전한 JSON 명령 미리보기 하나를 제안해줘."},
        {"ai.prompt.chain", "{scope} 현재 소리 역할에 맞는 인서트/센드 체인을 추천하고, 바로 적용해도 안전한 변경은 JSON 명령 미리보기로 하나만 제안해줘."},
        {"ai.prompt.clip", "{scope} 선택 클립의 소스 종류, 노이즈/클리핑/무음/편집 지점을 분석하고 필요한 오프라인 분석 작업을 제안해줘."},
        {"ai.prompt.record", "{scope} 다음 녹음 또는 재녹음에서 체크해야 할 입력 레벨, 노이즈, 모니터링, 헤드룸을 짧게 코칭해줘."},
        {"ai.status.quick_prompt", "요청 프리셋을 입력했습니다 · 필요하면 문장을 수정한 뒤 실행 또는 Ollama를 선택하세요"},
        {"ai.prompt.placeholder", "가사 추출, stem 분석, 믹스 조언, 안전한 편집을 요청..."},
        {"ai.prompt.tooltip", "선택 입력입니다. 기본 실행은 로컬 분석을 먼저 쓰고, Ollama는 선택 사항입니다."},
        {"ai.run_primary", "실행"},
        {"ai.run_primary.tooltip", "선택 대상의 로컬 AI 분석을 큐에 넣습니다. Apple Silicon에서는 Apple Neural Engine/Core ML을 우선 사용합니다."},
        {"ai.ask_ollama", "Ollama 요청"},
        {"ai.ask_ollama.tooltip", "입력한 요청을 로컬 Ollama 사이드카에 보냅니다."},
        {"ai.engine.primary", "엔진: Apple Neural Engine/Core ML 우선 · Windows는 GPU · Ollama는 선택"},
        {"ai.engine.badges", "기본 로컬 엔진: ANE/Core ML · GPU · 선택 Ollama"},
        {"ai.prepared_jobs", "준비된 작업:"},
        {"ai.workflow.clip", "흐름: 이 클립은 stem 분리 -> 가사 전사 -> 태그/검색 작업을 큐에 넣을 수 있습니다."},
        {"ai.workflow.track", "흐름: 이 채널은 트랙 분석, 전사, 임베딩 작업이 준비되어 있습니다."},
        {"ai.workflow.mix", "흐름: 전체 믹스 진단과 임베딩 작업이 준비되어 있습니다."},
        {"ai.button.stem_magic", "StemMagic"},
        {"ai.button.stage_chain", "체인 준비"},
        {"ai.button.apply", "적용"},
        {"ai.button.reject", "거절"},
        {"ai.button.save_memory", "메모리 저장"},
        {"ai.button.queue", "작업 큐"},
        {"ai.button.snapshot", "스냅샷"},
        {"ai.button.show_report", "상세 보기"},
        {"ai.button.show_report.tooltip", "필요할 때만 기술적인 AI 리포트를 표시합니다."},
        {"ai.button.copy_report", "리포트 복사"},
        {"ai.button.copy_report.tooltip", "상세 AI 리포트를 클립보드에 복사합니다."},
        {"ai.status.ready", "준비됨 · 실행할 때만 로컬 분석을 큐에 넣습니다"},
        {"ai.status.report_visible", "상세 리포트 표시 중"},
        {"ai.no_report.body", "아직 표시할 상세 AI 리포트가 없습니다."},
        {"ai.status.request_sent", "Ollama에 요청을 보냈습니다..."},
        {"ai.status.unavailable", "Ollama에 연결할 수 없습니다"},
        {"ai.status.parse_failed", "Ollama 응답 해석 실패"},
        {"ai.status.response_ready_preview", "AI 응답 준비됨 · 미리보기 감지"},
        {"ai.status.response_ready", "AI 응답 준비됨"},
        {"ai.status.no_preview", "적용할 AI 명령 미리보기가 없습니다"},
        {"ai.status.preview_rejected", "미리보기 거절됨"},
        {"ai.status.unsupported_preview", "직접 적용할 수 없음"},
        {"ai.status.no_change", "변경 없음"},
        {"ai.status.preview_applied", "AI 미리보기 적용됨"},
        {"ai.status.preview_rejected_user", "AI 미리보기를 거절했습니다"},
        {"ai.status.memory_failed", "AI 메모리 저장 실패"},
        {"ai.status.memory_saved", "AI 메모리 저장됨"},
        {"ai.status.no_external_jobs", "준비된 외부 AI 작업이 없습니다"},
        {"ai.status.external_queue_staged", "외부 AI 작업 큐 준비됨"},
        {"ai.status.no_chain", "준비할 체인 추천이 없습니다"},
        {"ai.status.chain_not_staged", "체인 준비 안 됨"},
        {"ai.status.chain_staged", "AI 체인 준비됨"},
        {"ai.report_copied", "AI 리포트를 복사했습니다"},
        {"ai.snapshot_copied", "AI 스냅샷을 복사했습니다"},
        {"ai.no_content", "응답 내용이 없습니다"},
        {"ai.invalid_preview_json", "올바르지 않은 미리보기 JSON입니다"},
        {"ai.unsupported_preview.body", "이 미리보기는 외부 작업이거나 아직 직접 적용할 수 없는 AI 동작입니다."},
        {"ai.no_change.body", "AI 명령은 유효했지만 프로젝트 변경 사항은 없었습니다."},
        {"ai.applied_preview.body", "AI 미리보기를 적용했습니다:\n{json}"},
        {"ai.saved_memory.body", "AI 믹스 메모리를 저장했습니다:\n{path}"},
        {"ai.external_queue.body", "사이드카 요청으로 준비된 외부 AI 작업:\n"},
        {"ai.external_queue.item", "- {engine} / {mode}\n  입력: {input}\n  출력: {output}\n"},
        {"ai.chain.editable_only", "추천 체인은 편집 가능한 오디오/악기/Aux 트랙에만 준비할 수 있습니다."},
        {"ai.chain.no_slots", "추가된 인서트 슬롯이 없습니다."},
        {"ai.chain.staged.body", "{track} 트랙에 AI 체인용 빈 인서트 슬롯 {count}개를 준비했습니다.\n추천 프로세서는 참고 메모로만 남기며, 플러그인은 자동 로드하지 않습니다."},
        {"ai.role.vocal", "보컬"},
        {"ai.role.drums", "드럼"},
        {"ai.role.bass", "베이스"},
        {"ai.role.guitar", "기타"},
        {"ai.role.keys", "건반/신스"},
        {"ai.role.cleanup", "정리/복원"},
        {"ai.role.general", "일반"},
        {"ai.severity.info", "정보"},
        {"ai.severity.warning", "주의"},
        {"ai.severity.critical", "위험"},
        {"ai.processor.gain_trim", "게인 정리"},
        {"ai.processor.subtractive_eq", "감산 EQ"},
        {"ai.processor.compressor", "컴프레서"},
        {"ai.processor.ambience_send", "공간계 센드"},
        {"ai.processor.de_esser", "디에서"},
        {"ai.processor.saturation", "새추레이션"},
        {"ai.processor.reverb_send", "리버브 센드"},
        {"ai.processor.transient_shaper", "트랜지언트 셰이퍼"},
        {"ai.processor.bus_compressor", "버스 컴프레서"},
        {"ai.processor.parallel_compression_send", "병렬 컴프 센드"},
        {"ai.processor.low_cleanup_eq", "저역 정리 EQ"},
        {"ai.processor.sidechain_candidate", "사이드체인 후보"},
        {"ai.processor.high_pass_eq", "하이패스 EQ"},
        {"ai.processor.tone_eq", "톤 EQ"},
        {"ai.processor.room_send", "룸 센드"},
        {"ai.processor.stereo_width_check", "스테레오 폭 점검"},
        {"ai.processor.gentle_compressor", "가벼운 컴프레서"},
        {"ai.processor.delay_or_reverb_send", "딜레이/리버브 센드"},
        {"ai.processor.noise_reduction_candidate", "노이즈 감소 후보"},
        {"ai.processor.manual_edit_review", "수동 편집 점검"},
        {"ai.processor.clip_repair_review", "클립 복원/재녹음 점검"},
        {"ai.processor.normalize_or_clip_gain", "노멀라이즈/클립 게인"},
        {"ai.rationale.general", "보수적인 기본 체인이라 AI 변경 내용을 검토하기 쉽습니다."},
        {"ai.rationale.vocal", "보컬은 정리, 다이내믹 제어, 존재감, 절제된 공간계 센드가 보통 필요합니다."},
        {"ai.rationale.drums", "드럼은 트랜지언트 제어와 병렬 압축으로 밀도를 더하기 좋습니다."},
        {"ai.rationale.bass", "베이스는 저역을 안정시키고 작은 스피커에서도 들릴 배음을 드러내는 것이 좋습니다."},
        {"ai.rationale.guitar", "기타는 대역 정리와 믹스 안에서 어울리는 공간감이 중요합니다."},
        {"ai.rationale.keys", "건반은 강한 다이내믹 처리보다 공간감과 폭 관리가 더 중요한 경우가 많습니다."},
        {"ai.rationale.cleanup", "정리/복원 소재는 음악적 처리 전에 먼저 수리하는 편이 좋습니다."},
        // 도움말 모드 툴팁 (? 도움말 토글이 켜져 있을 때 표시).
        {"help.split", "커서 위치에서 클립 분할 (B)"},
        {"help.heal", "분할된 클립 붙이기 (H)"},
        {"help.delete", "선택 삭제"},
        {"help.copy", "복사"},
        {"help.cut", "잘라내기"},
        {"help.paste", "붙여넣기"},
        {"help.duplicate", "복제"},
        {"help.marker", "재생 헤드에 마커 추가 (⌘M)"},
        {"help.add_audio", "오디오 트랙 추가"},
        {"help.add_instrument", "악기 트랙 추가"},
        {"help.delete_track", "트랙 삭제"},
        {"help.range", "구간 편집 (자르기 / 지우기 / 삽입)"},
        {"help.zoom_in", "확대"},
        {"help.zoom_out", "축소"},
        {"help.zoom_fit", "화면 맞춤"},
        {"help.grid", "그리드 해상도 (스냅 단위)"},
        {"help.mixer_io", "입출력 라우팅 (I/O) 표시"},
        {"help.mixer_inserts", "인서트 슬롯 표시"},
        {"help.mixer_sends", "센드 표시"},
        {"help.mixer_memo", "채널 메모 표시"},
        {"help.pan_law", "모노 트랙 팬 법칙 (프로젝트 설정)"},
        {"help.automation_mode", "자동화 모드 순환 (Read → Touch → Latch → Write → Off)"},
        {"help.channel_wide", "채널 넓게"},
        {"help.channel_narrow", "채널 좁게"},
        {"help.mode_on", "도움말 모드: 켜면 버튼에 마우스를 올렸을 때 설명이 나옵니다"},
        {"help.mode_off", "도움말 모드 끄기"},
    };
    return strings;
}

const Table& japaneseStrings() {
    static const Table strings = {
        {"common.close", "閉じる"},
        {"ai.title", "AIアシスタント"},
        {"ai.project.untitled", "名称未設定"},
        {"ai.summary", "プロジェクト {project} · トラック {tracks} · オーディオ {audio} · クリップ {clips} · {bpm} bpm"},
        {"ai.safe_mode", "安全モード {state} · ローカルAI: {decision} · {message}"},
        {"ai.state.idle", "待機"},
        {"ai.state.playback", "再生中"},
        {"ai.state.recording", "録音中"},
        {"ai.decision.allow_now", "すぐ実行可能"},
        {"ai.decision.queue_until_idle", "待機後に実行"},
        {"ai.decision.block", "ブロック"},
        {"ai.guard.allowed", "現在のDAW安全ポリシーではローカルAIを使用できます。"},
        {"ai.guard.recording", "録音中のため、リアルタイム録音を守る目的でローカルAIを後で実行します。"},
        {"ai.guard.transport", "再生中のため、軽量でないローカルAIは停止後に実行します。"},
        {"ai.guard.disabled", "ローカルAIが無効です。推論なしでDAW機能を維持します。"},
        {"ai.guard.resource_pressure", "システム負荷が高いため、現在ローカルAI推論をブロックします。"},
        {"ai.selected_clip", "選択クリップ: {clip} · トラック {track}"},
        {"ai.selected_clip.none", "選択クリップ: なし · プロジェクト全体の文脈のみ"},
        {"ai.audio.summary", "オーディオ: {duration}秒 · {channels} ch · {sampleRate} Hz · ピーク {peak} · RMS {rms} · クレスト {crest} · セントロイド {centroid} Hz"},
        {"ai.audio.large", "オーディオ: 大きいファイルのためパネル分析をスキップします。オフライン分析に送ってください。"},
        {"ai.audio.offline", "オーディオ: オフライン分析を推奨します ({reason})"},
        {"ai.role", "役割: {role}"},
        {"ai.chain", "推奨チェーン: "},
        {"ai.why", "理由: {reason}"},
        {"ai.diagnostics", "診断:"},
        {"ai.edit_suggestions", "編集提案:"},
        {"ai.external_jobs_ready", "準備済みの外部ジョブ:"},
        {"ai.idea_generator", "アイデア生成: {engine} / {mode}"},
        {"ai.prompt.default", "ボーカル/ミックスの状態を見て、安全なJSONコマンドプレビューを1つ提案してください。"},
        {"ai.context.clip", "現在の対象: 選択クリップ {clip} · トラック {track} · 聴く経路: クリップ元/トラック出力候補"},
        {"ai.context.track", "現在の対象: 選択トラック/チャンネル {track} · 聴く経路: トラック出力"},
        {"ai.context.master", "現在の対象: 選択マスターチャンネル {track} · 聴く経路: マスター出力"},
        {"ai.context.mix", "現在の対象: ミックス全体 · 聴く経路: マスター出力"},
        {"ai.scope.clip", "選択クリップ {clip} とそのトラック {track} を基準に"},
        {"ai.scope.track", "選択トラック/チャンネル {track} を基準に"},
        {"ai.scope.master", "選択マスター/ミックス全体を基準に"},
        {"ai.scope.mix", "現在のプロジェクトのミックス全体を基準に"},
        {"ai.quick.diagnose", "ミックス診断"},
        {"ai.quick.chain", "チェーン提案"},
        {"ai.quick.clip", "クリップ分析"},
        {"ai.quick.record", "録音コーチ"},
        {"ai.prompt.diagnose", "{scope} レベル、ヘッドルーム、帯域バランス、マスキング、ダイナミクスの問題を診断し、安全なJSONコマンドプレビューを1つ提案してください。"},
        {"ai.prompt.chain", "{scope} 現在の音の役割に合うインサート/センドチェーンを提案し、直接変更が安全な場合はJSONコマンドプレビューを1つだけ提案してください。"},
        {"ai.prompt.clip", "{scope} ソース種類、ノイズ、クリッピング、無音、編集ポイントを分析し、必要なオフライン分析ジョブを提案してください。"},
        {"ai.prompt.record", "{scope} 次の録音または再録で確認すべき入力レベル、ノイズ、モニタリング、ヘッドルームを短くコーチしてください。"},
        {"ai.status.quick_prompt", "リクエストプリセットを入力しました · 必要なら編集して実行またはOllamaを選んでください"},
        {"ai.prompt.placeholder", "歌詞抽出、stem解析、ミックス助言、安全な編集を依頼..."},
        {"ai.prompt.tooltip", "任意入力です。既定の実行はローカル解析を優先し、Ollamaは任意です。"},
        {"ai.run_primary", "実行"},
        {"ai.run_primary.tooltip", "選択対象のローカルAI解析をキューに入れます。Apple SiliconではApple Neural Engine/Core MLを優先します。"},
        {"ai.ask_ollama", "Ollamaに依頼"},
        {"ai.ask_ollama.tooltip", "入力した依頼をローカルOllamaサイドカーへ送ります。"},
        {"ai.engine.primary", "エンジン: Apple Neural Engine/Core ML優先 · WindowsはGPU · Ollamaは任意"},
        {"ai.engine.badges", "既定ローカルエンジン: ANE/Core ML · GPU · 任意Ollama"},
        {"ai.prepared_jobs", "準備済みジョブ:"},
        {"ai.workflow.clip", "フロー: このクリップはstem分離 -> 歌詞文字起こし -> タグ/検索ジョブをキューできます。"},
        {"ai.workflow.track", "フロー: このチャンネルはトラック解析、文字起こし、埋め込みジョブが準備済みです。"},
        {"ai.workflow.mix", "フロー: フルミックス診断と埋め込みジョブが準備済みです。"},
        {"ai.button.stem_magic", "StemMagic"},
        {"ai.button.stage_chain", "チェーン準備"},
        {"ai.button.apply", "適用"},
        {"ai.button.reject", "拒否"},
        {"ai.button.save_memory", "メモリ保存"},
        {"ai.button.queue", "作業キュー"},
        {"ai.button.snapshot", "スナップショット"},
        {"ai.button.show_report", "詳細"},
        {"ai.button.show_report.tooltip", "必要な時だけ技術的なAIレポートを表示します。"},
        {"ai.button.copy_report", "レポートコピー"},
        {"ai.button.copy_report.tooltip", "詳細AIレポートをクリップボードへコピーします。"},
        {"ai.status.ready", "準備完了 · 実行時だけローカル解析をキューします"},
        {"ai.status.report_visible", "詳細レポートを表示中"},
        {"ai.no_report.body", "表示できる詳細AIレポートはまだありません。"},
        {"ai.status.request_sent", "Ollamaにリクエストを送信しました..."},
        {"ai.status.unavailable", "Ollamaに接続できません"},
        {"ai.status.parse_failed", "Ollama応答の解析に失敗しました"},
        {"ai.status.response_ready_preview", "AI応答準備完了 · プレビュー検出"},
        {"ai.status.response_ready", "AI応答準備完了"},
        {"ai.status.no_preview", "適用するAIコマンドプレビューがありません"},
        {"ai.status.preview_rejected", "プレビュー拒否"},
        {"ai.status.unsupported_preview", "直接適用できません"},
        {"ai.status.no_change", "変更なし"},
        {"ai.status.preview_applied", "AIプレビュー適用済み"},
        {"ai.status.preview_rejected_user", "AIプレビューを拒否しました"},
        {"ai.status.memory_failed", "AIメモリ保存失敗"},
        {"ai.status.memory_saved", "AIメモリ保存済み"},
        {"ai.status.no_external_jobs", "準備済みの外部AIジョブはありません"},
        {"ai.status.external_queue_staged", "外部AIジョブキュー準備完了"},
        {"ai.status.no_chain", "準備するチェーン提案がありません"},
        {"ai.status.chain_not_staged", "チェーン未準備"},
        {"ai.status.chain_staged", "AIチェーン準備完了"},
        {"ai.report_copied", "AIレポートをコピーしました"},
        {"ai.snapshot_copied", "AIスナップショットをコピーしました"},
        {"ai.no_content", "応答内容がありません"},
        {"ai.invalid_preview_json", "無効なプレビューJSONです"},
        {"ai.unsupported_preview.body", "このプレビューは外部ジョブ、またはまだ直接適用できないAIアクションです。"},
        {"ai.no_change.body", "AIコマンドは有効でしたが、プロジェクトは変更されませんでした。"},
        {"ai.applied_preview.body", "AIプレビューを適用しました:\n{json}"},
        {"ai.saved_memory.body", "AIミックスメモリを保存しました:\n{path}"},
        {"ai.external_queue.body", "サイドカー要求として準備済みの外部AIジョブ:\n"},
        {"ai.external_queue.item", "- {engine} / {mode}\n  入力: {input}\n  出力: {output}\n"},
        {"ai.chain.editable_only", "推奨チェーンは編集可能なオーディオ/インストゥルメント/Auxトラックにのみ準備できます。"},
        {"ai.chain.no_slots", "追加されたインサートスロットはありません。"},
        {"ai.chain.staged.body", "{track}トラックにAIチェーン用の空インサートスロットを{count}個準備しました。\n推奨プロセッサは確認メモとして残し、プラグインは自動ロードしません。"},
        {"ai.role.vocal", "ボーカル"},
        {"ai.role.drums", "ドラム"},
        {"ai.role.bass", "ベース"},
        {"ai.role.guitar", "ギター"},
        {"ai.role.keys", "鍵盤/シンセ"},
        {"ai.role.cleanup", "クリーンアップ/修復"},
        {"ai.role.general", "一般"},
        {"ai.severity.info", "情報"},
        {"ai.severity.warning", "注意"},
        {"ai.severity.critical", "重大"},
        {"ai.processor.gain_trim", "ゲイン調整"},
        {"ai.processor.subtractive_eq", "減算EQ"},
        {"ai.processor.compressor", "コンプレッサー"},
        {"ai.processor.ambience_send", "アンビエンスセンド"},
        {"ai.processor.de_esser", "ディエッサー"},
        {"ai.processor.saturation", "サチュレーション"},
        {"ai.processor.reverb_send", "リバーブセンド"},
        {"ai.processor.transient_shaper", "トランジェントシェイパー"},
        {"ai.processor.bus_compressor", "バスコンプレッサー"},
        {"ai.processor.parallel_compression_send", "パラレルコンプセンド"},
        {"ai.processor.low_cleanup_eq", "低域整理EQ"},
        {"ai.processor.sidechain_candidate", "サイドチェイン候補"},
        {"ai.processor.high_pass_eq", "ハイパスEQ"},
        {"ai.processor.tone_eq", "トーンEQ"},
        {"ai.processor.room_send", "ルームセンド"},
        {"ai.processor.stereo_width_check", "ステレオ幅チェック"},
        {"ai.processor.gentle_compressor", "軽いコンプレッサー"},
        {"ai.processor.delay_or_reverb_send", "ディレイ/リバーブセンド"},
        {"ai.processor.noise_reduction_candidate", "ノイズ低減候補"},
        {"ai.processor.manual_edit_review", "手動編集確認"},
        {"ai.processor.clip_repair_review", "クリップ修復/再録確認"},
        {"ai.processor.normalize_or_clip_gain", "ノーマライズ/クリップゲイン"},
        {"ai.rationale.general", "保守的な基本チェーンなので、AI変更を確認しやすくします。"},
        {"ai.rationale.vocal", "ボーカルは整理、ダイナミクス制御、存在感、抑えた空間センドが必要になりやすいです。"},
        {"ai.rationale.drums", "ドラムはトランジェント制御とパラレル密度で効果が出やすいです。"},
        {"ai.rationale.bass", "ベースは低域を安定させ、小さいスピーカーでも聞こえる倍音を出すことが重要です。"},
        {"ai.rationale.guitar", "ギターは帯域整理とミックス内で合う空間感が重要です。"},
        {"ai.rationale.keys", "鍵盤は強いダイナミクス処理より、空間と幅の管理が重要な場合が多いです。"},
        {"ai.rationale.cleanup", "クリーンアップ素材は音楽的処理の前に修復するのが安全です。"},
    };
    return strings;
}

const Table& chineseStrings() {
    static const Table strings = {
        {"common.close", "关闭"},
        {"ai.title", "AI 助手"},
        {"ai.project.untitled", "未命名"},
        {"ai.summary", "项目 {project} · {tracks} 条轨道 · {audio} 条音频 · {clips} 个片段 · {bpm} bpm"},
        {"ai.safe_mode", "安全模式 {state} · 本地 AI: {decision} · {message}"},
        {"ai.state.idle", "待机"},
        {"ai.state.playback", "播放中"},
        {"ai.state.recording", "录音中"},
        {"ai.decision.allow_now", "可立即执行"},
        {"ai.decision.queue_until_idle", "空闲后执行"},
        {"ai.decision.block", "已阻止"},
        {"ai.guard.allowed", "根据当前 DAW 安全策略，可以使用本地 AI。"},
        {"ai.guard.recording", "正在录音，为保护实时录制，将延后执行本地 AI。"},
        {"ai.guard.transport", "正在播放，非轻量本地 AI 将在停止后执行。"},
        {"ai.guard.disabled", "本地 AI 已关闭，DAW 将在无推理状态下继续工作。"},
        {"ai.guard.resource_pressure", "系统资源压力较高，暂时阻止本地 AI 推理。"},
        {"ai.selected_clip", "选中片段: {clip} · 轨道 {track}"},
        {"ai.selected_clip.none", "选中片段: 无 · 仅使用项目级上下文"},
        {"ai.audio.summary", "音频: {duration} 秒 · {channels} ch · {sampleRate} Hz · 峰值 {peak} · RMS {rms} · 峰均比 {crest} · 质心 {centroid} Hz"},
        {"ai.audio.large", "音频: 文件较大，面板分析已跳过。请改用离线分析任务。"},
        {"ai.audio.offline", "音频: 建议进行离线分析 ({reason})"},
        {"ai.role", "角色: {role}"},
        {"ai.chain", "推荐链: "},
        {"ai.why", "原因: {reason}"},
        {"ai.diagnostics", "诊断:"},
        {"ai.edit_suggestions", "编辑建议:"},
        {"ai.external_jobs_ready", "已准备的外部任务:"},
        {"ai.idea_generator", "创意生成: {engine} / {mode}"},
        {"ai.prompt.default", "查看人声/混音状态，并提出一个安全的 JSON 命令预览。"},
        {"ai.context.clip", "当前目标: 选中片段 {clip} · 轨道 {track} · 监听路径: 片段源/轨道输出候选"},
        {"ai.context.track", "当前目标: 选中轨道/通道 {track} · 监听路径: 轨道输出"},
        {"ai.context.master", "当前目标: 选中母线通道 {track} · 监听路径: 母线输出"},
        {"ai.context.mix", "当前目标: 整体混音 · 监听路径: 母线输出"},
        {"ai.scope.clip", "基于当前选中片段 {clip} 及其轨道 {track}，"},
        {"ai.scope.track", "基于当前选中轨道/通道 {track}，"},
        {"ai.scope.master", "基于当前选中的母线/整体混音，"},
        {"ai.scope.mix", "基于当前项目的整体混音，"},
        {"ai.quick.diagnose", "混音诊断"},
        {"ai.quick.chain", "链推荐"},
        {"ai.quick.clip", "片段分析"},
        {"ai.quick.record", "录音教练"},
        {"ai.prompt.diagnose", "{scope}诊断电平、余量、频段平衡、遮蔽和动态问题，并提出一个安全的 JSON 命令预览。"},
        {"ai.prompt.chain", "{scope}推荐适合当前声音角色的插入/发送链；如有安全的直接更改，只提出一个 JSON 命令预览。"},
        {"ai.prompt.clip", "{scope}分析源类型、噪声、削波、静音和编辑点，并提出所需的离线分析任务。"},
        {"ai.prompt.record", "{scope}简短指导下一次录音或重录需要检查的输入电平、噪声、监听和余量。"},
        {"ai.status.quick_prompt", "已填入请求预设 · 如有需要请编辑文本，然后选择执行或 Ollama"},
        {"ai.prompt.placeholder", "请求歌词提取、stem 分析、混音建议或安全编辑..."},
        {"ai.prompt.tooltip", "可选输入。默认执行会优先使用本地分析，Ollama 为可选。"},
        {"ai.run_primary", "执行"},
        {"ai.run_primary.tooltip", "将所选目标的本地 AI 分析加入队列。Apple Silicon 上优先使用 Apple Neural Engine/Core ML。"},
        {"ai.ask_ollama", "请求 Ollama"},
        {"ai.ask_ollama.tooltip", "将输入的请求发送到本地 Ollama sidecar。"},
        {"ai.engine.primary", "引擎: 优先 Apple Neural Engine/Core ML · Windows 使用 GPU · Ollama 可选"},
        {"ai.engine.badges", "默认本地引擎: ANE/Core ML · GPU · 可选 Ollama"},
        {"ai.prepared_jobs", "已准备任务:"},
        {"ai.workflow.clip", "流程: 此片段可加入 stem 分离 -> 歌词转写 -> 标签/搜索任务。"},
        {"ai.workflow.track", "流程: 此通道已准备轨道分析、转写和嵌入任务。"},
        {"ai.workflow.mix", "流程: 已准备整体混音诊断和嵌入任务。"},
        {"ai.button.stem_magic", "StemMagic"},
        {"ai.button.stage_chain", "准备链"},
        {"ai.button.apply", "应用"},
        {"ai.button.reject", "拒绝"},
        {"ai.button.save_memory", "保存记忆"},
        {"ai.button.queue", "任务队列"},
        {"ai.button.snapshot", "快照"},
        {"ai.button.show_report", "详情"},
        {"ai.button.show_report.tooltip", "仅在需要时显示技术 AI 报告。"},
        {"ai.button.copy_report", "复制报告"},
        {"ai.button.copy_report.tooltip", "将详细 AI 报告复制到剪贴板。"},
        {"ai.status.ready", "就绪 · 仅在执行时将本地 AI 分析加入队列"},
        {"ai.status.report_visible", "正在显示详细报告"},
        {"ai.no_report.body", "尚无可显示的详细 AI 报告。"},
        {"ai.status.request_sent", "已向 Ollama 发送请求..."},
        {"ai.status.unavailable", "无法连接 Ollama"},
        {"ai.status.parse_failed", "Ollama 响应解析失败"},
        {"ai.status.response_ready_preview", "AI 响应就绪 · 已检测到预览"},
        {"ai.status.response_ready", "AI 响应就绪"},
        {"ai.status.no_preview", "没有可应用的 AI 命令预览"},
        {"ai.status.preview_rejected", "预览已拒绝"},
        {"ai.status.unsupported_preview", "无法直接应用"},
        {"ai.status.no_change", "没有更改"},
        {"ai.status.preview_applied", "AI 预览已应用"},
        {"ai.status.preview_rejected_user", "AI 预览已拒绝"},
        {"ai.status.memory_failed", "AI 记忆保存失败"},
        {"ai.status.memory_saved", "AI 记忆已保存"},
        {"ai.status.no_external_jobs", "没有已准备的外部 AI 任务"},
        {"ai.status.external_queue_staged", "外部 AI 任务队列已准备"},
        {"ai.status.no_chain", "没有可准备的链建议"},
        {"ai.status.chain_not_staged", "链未准备"},
        {"ai.status.chain_staged", "AI 链已准备"},
        {"ai.report_copied", "AI 报告已复制"},
        {"ai.snapshot_copied", "AI 快照已复制"},
        {"ai.no_content", "没有响应内容"},
        {"ai.invalid_preview_json", "无效的预览 JSON"},
        {"ai.unsupported_preview.body", "此预览是外部任务，或暂时不支持直接应用。"},
        {"ai.no_change.body", "AI 命令有效，但项目没有发生更改。"},
        {"ai.applied_preview.body", "已应用 AI 预览:\n{json}"},
        {"ai.saved_memory.body", "已保存 AI 混音记忆:\n{path}"},
        {"ai.external_queue.body", "作为 sidecar 请求准备的外部 AI 任务:\n"},
        {"ai.external_queue.item", "- {engine} / {mode}\n  输入: {input}\n  输出: {output}\n"},
        {"ai.chain.editable_only", "推荐链只能准备到可编辑的音频/乐器/Aux 轨道。"},
        {"ai.chain.no_slots", "没有添加插入槽。"},
        {"ai.chain.staged.body", "已在 {track} 轨道准备 {count} 个 AI 链空插入槽。\n推荐处理器仅作为审核备注保留，不会自动加载插件。"},
        {"ai.role.vocal", "人声"},
        {"ai.role.drums", "鼓"},
        {"ai.role.bass", "贝斯"},
        {"ai.role.guitar", "吉他"},
        {"ai.role.keys", "键盘/合成器"},
        {"ai.role.cleanup", "清理/修复"},
        {"ai.role.general", "通用"},
        {"ai.severity.info", "信息"},
        {"ai.severity.warning", "注意"},
        {"ai.severity.critical", "严重"},
        {"ai.processor.gain_trim", "增益整理"},
        {"ai.processor.subtractive_eq", "削减 EQ"},
        {"ai.processor.compressor", "压缩器"},
        {"ai.processor.ambience_send", "空间发送"},
        {"ai.processor.de_esser", "齿音消除"},
        {"ai.processor.saturation", "饱和"},
        {"ai.processor.reverb_send", "混响发送"},
        {"ai.processor.transient_shaper", "瞬态塑形器"},
        {"ai.processor.bus_compressor", "总线压缩器"},
        {"ai.processor.parallel_compression_send", "并行压缩发送"},
        {"ai.processor.low_cleanup_eq", "低频整理 EQ"},
        {"ai.processor.sidechain_candidate", "侧链候选"},
        {"ai.processor.high_pass_eq", "高通 EQ"},
        {"ai.processor.tone_eq", "音色 EQ"},
        {"ai.processor.room_send", "房间发送"},
        {"ai.processor.stereo_width_check", "立体声宽度检查"},
        {"ai.processor.gentle_compressor", "轻度压缩器"},
        {"ai.processor.delay_or_reverb_send", "延迟/混响发送"},
        {"ai.processor.noise_reduction_candidate", "降噪候选"},
        {"ai.processor.manual_edit_review", "手动编辑检查"},
        {"ai.processor.clip_repair_review", "片段修复/重录检查"},
        {"ai.processor.normalize_or_clip_gain", "标准化/片段增益"},
        {"ai.rationale.general", "保守的通用链便于审核 AI 更改。"},
        {"ai.rationale.vocal", "人声通常需要清理、动态控制、存在感以及受控的空间发送。"},
        {"ai.rationale.drums", "鼓轨适合通过瞬态控制和并行密度获得效果。"},
        {"ai.rationale.bass", "贝斯链应稳定低频，并在小音箱上呈现可听的泛音。"},
        {"ai.rationale.guitar", "吉他通常需要频段控制和适合上下文的空间感。"},
        {"ai.rationale.keys", "键盘通常比重度动态处理更需要空间与宽度管理。"},
        {"ai.rationale.cleanup", "清理素材应先修复，再进行音乐化处理。"},
    };
    return strings;
}

const Table& tableForLanguage(UiLanguage language) {
    switch (language) {
        case UiLanguage::Korean: return koreanStrings();
        case UiLanguage::Japanese: return japaneseStrings();
        case UiLanguage::ChineseSimplified: return chineseStrings();
        case UiLanguage::English: return englishStrings();
    }
    return englishStrings();
}

} // namespace

UiLanguage uiLanguageFromLocaleTag(const std::string& localeTag) {
    const std::string tag = normalizeLocaleTag(localeTag);
    if (tag.rfind("ko", 0) == 0) return UiLanguage::Korean;
    if (tag.rfind("ja", 0) == 0) return UiLanguage::Japanese;
    if (tag.rfind("zh", 0) == 0) return UiLanguage::ChineseSimplified;
    if (tag.rfind("en", 0) == 0) return UiLanguage::English;
    return UiLanguage::English;
}

void setUiLanguageFromLocaleTag(const std::string& localeTag) {
    setUiLanguage(uiLanguageFromLocaleTag(localeTag));
}

void setUiLanguage(UiLanguage language) {
    std::lock_guard<std::mutex> lock(gLanguageMutex);
    gLanguage = language;
}

UiLanguage currentUiLanguage() {
    std::lock_guard<std::mutex> lock(gLanguageMutex);
    return gLanguage;
}

std::string currentUiLanguageCode() {
    switch (currentUiLanguage()) {
        case UiLanguage::Korean: return "ko";
        case UiLanguage::Japanese: return "ja";
        case UiLanguage::ChineseSimplified: return "zh-Hans";
        case UiLanguage::English: return "en";
    }
    return "en";
}

std::string tr(const std::string& key) {
    const UiLanguage language = currentUiLanguage();
    const auto& table = tableForLanguage(language);
    const auto localized = table.find(key);
    if (localized != table.end()) {
        return std::string(localized->second);
    }
    const auto& fallback = englishStrings();
    const auto english = fallback.find(key);
    if (english != fallback.end()) {
        return std::string(english->second);
    }
    return key;
}

} // namespace neuracoust::daw
