#!/usr/bin/env python3
"""Bake the measured speaker response curves from resources/speaker_model_dataset.json into a
compact C++ source (src/audio/SpeakerProfiles.generated.cpp) so the virtual-monitor engine can
look them up with no runtime JSON parser or bundled resource. Re-run when the dataset changes:

    python3 tools/gen_speaker_profiles.py
"""
import json, os, sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC = os.path.join(ROOT, "resources", "speaker_model_dataset.json")
OUT = os.path.join(ROOT, "src", "audio", "SpeakerProfiles.generated.cpp")

data = json.load(open(SRC))
entries = []
for x in data:
    rc = x.get("response_curve") or {}
    pts = rc.get("points")
    if not isinstance(pts, list) or not pts:
        continue
    # Keep only finite (freq, db) pairs, ascending in frequency.
    clean = []
    for p in pts:
        if not (isinstance(p, list) and len(p) == 2):
            continue
        f, db = p
        if isinstance(f, (int, float)) and isinstance(db, (int, float)):
            clean.append((float(f), float(db)))
    if len(clean) >= 8:
        entries.append((x["catalog_name"], clean))

def esc(s):
    return s.replace("\\", "\\\\").replace('"', '\\"')

lines = []
lines.append("// GENERATED by tools/gen_speaker_profiles.py — do not edit by hand.")
lines.append('#include "audio/SpeakerProfiles.h"')
lines.append("")
lines.append("namespace neuracoust::daw {")
lines.append("namespace {")
lines.append("struct ProfileEntry { const char* name; const double* data; int count; };")
for i, (name, curve) in enumerate(entries):
    nums = ",".join(f"{f:g},{db:g}" for f, db in curve)
    lines.append(f"static const double kProfile{i}[] = {{{nums}}};")
lines.append("static const ProfileEntry kProfiles[] = {")
for i, (name, curve) in enumerate(entries):
    lines.append(f'    {{"{esc(name)}", kProfile{i}, {len(curve)}}},')
lines.append("};")
lines.append("} // namespace")
lines.append("")
lines.append("ResponseCurve speakerProfileCurve(const std::string& catalogName) {")
lines.append("    for (const auto& e : kProfiles) {")
lines.append("        if (catalogName == e.name) {")
lines.append("            ResponseCurve c; c.reserve(static_cast<size_t>(e.count));")
lines.append("            for (int i = 0; i < e.count; ++i) c.push_back({e.data[i * 2], e.data[i * 2 + 1]});")
lines.append("            return c;")
lines.append("        }")
lines.append("    }")
lines.append("    return {};")
lines.append("}")
lines.append("")
lines.append("std::vector<std::string> speakerProfilesWithCurve() {")
lines.append("    std::vector<std::string> names;")
lines.append("    names.reserve(sizeof(kProfiles) / sizeof(kProfiles[0]));")
lines.append("    for (const auto& e : kProfiles) names.emplace_back(e.name);")
lines.append("    return names;")
lines.append("}")
lines.append("")
lines.append("} // namespace neuracoust::daw")
lines.append("")

open(OUT, "w").write("\n".join(lines))
print(f"wrote {OUT}: {len(entries)} measured speaker curves")
