#!/usr/bin/env python3
"""Bake measured audio-interface D/A frequency-response curves into a C++ profile
(src/audio/AudioInterfaceProfiles.generated.cpp) from the in-house test reports (시험성적서 HTML)
in docs/audio-interface-da-modeling-research/measurements/.

STRICT (per docs/audio-interface-da-modeling-research/claude_handoff.md):
  • Only REAL measured data becomes a profile — this parses the report's measured FR curve.
  • The curve is the interface's own measured deviation (report is 1 kHz-normalized). The monitor
    path applies the INVERSE (compensation) so monitoring is flattened for that D/A.

Each report renders the FR as an SVG <polyline>; the y-axis is calibrated from its "0 dB / +12 dB /
-12 dB" text labels, the x-axis is log 20 Hz–20 kHz across the plotted width.

Re-run when a measurement report is added/changed:
    python3 tools/gen_audio_interface_profiles.py
"""
import math
import os
import re

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
MEAS_DIR = os.path.join(ROOT, "docs", "audio-interface-da-modeling-research", "measurements")
OUT_CPP = os.path.join(ROOT, "src", "audio", "AudioInterfaceProfiles.generated.cpp")

# report filename stem (before "_시험성적서") -> catalog display name
NAME_MAP = {
    "Kurzweil UNiTE-2": "Kurzweil UNiTE-2",
}

F_LO, F_HI = 20.0, 20000.0


# Reference send level (dBFS) whose measured H2–H7 seed the harmonic waveshaper. A mid monitoring
# level — the harmonic character an engineer actually hears.
HARMONIC_REF_LEVEL = "-20 dBFS"


def parse_harmonics(html):
    """Return [c2..c7] linear amplitudes (fundamental = 1) from the per-level harmonic table at the
    reference level, or [] if the section/level is missing. Magnitude only (phase is inaudible at
    these depths and phase-exact synthesis is out of scope)."""
    i = html.find("레벨별")
    if i < 0:
        return []
    sec = html[i:i + 4000]
    cells = [re.sub(r"<[^>]+>", "", c).strip() for c in re.findall(r"<t[dh][^>]*>(.*?)</t[dh]>", sec, re.S)]
    rows = cells[5:]  # skip the 5-col header
    coeffs = {}
    for k in range(0, len(rows) - 4, 5):
        lvl, order, _freq, mag, _ph = rows[k:k + 5]
        if lvl != HARMONIC_REF_LEVEL:
            continue
        m = re.match(r"H(\d)", order)
        db = re.match(r"(-?\d+(?:\.\d+)?)", mag)
        if m and db:
            coeffs[int(m.group(1))] = 10.0 ** (float(db.group(1)) / 20.0)
    return [coeffs.get(n, 0.0) for n in range(2, 8)]  # c2..c7


def parse_report(path):
    """Return (catalog_name, [(freq, db), ...], [c2..c7]) from one 시험성적서 HTML."""
    html = open(path, encoding="utf-8").read()
    fn = os.path.basename(path)
    name = next((v for k, v in NAME_MAP.items() if k in fn), None)
    if name is None:  # fall back to the filename stem, minus the report suffix
        name = re.split(r"_?\s*시험성적서", os.path.splitext(fn)[0])[0].strip()

    # Isolate the frequency-response section (section 3) so we grab the right SVG.
    i = html.find("주파수 응답")
    sec = html[i:i + 8000] if i >= 0 else html

    # y calibration from the axis text labels: "<text ... y='Y'>0 dB</text>" etc.
    labels = {}
    for m in re.finditer(r"<text[^>]*y='([\d.]+)'[^>]*>\s*([+-]?\d+)\s*dB\s*</text>", sec):
        labels[float(m.group(1))] = float(m.group(2))
    if len(labels) < 2:
        raise SystemExit(f"{path}: could not read dB axis labels")
    ys = sorted(labels)
    y0, y1 = ys[0], ys[-1]
    d0, d1 = labels[y0], labels[y1]
    # dB(y) linear between the two extreme labels.
    def y_to_db(y):
        return d0 + (d1 - d0) * (y - y0) / (y1 - y0)

    # polyline points across the plot; x maps log 20 Hz .. 20 kHz over [xmin, xmax].
    pl = re.search(r"<polyline[^>]*points='([^']+)'", sec)
    if not pl:
        raise SystemExit(f"{path}: no FR polyline found")
    pts = []
    for tok in pl.group(1).split():
        xs, yss = tok.split(",")
        pts.append((float(xs), float(yss)))
    xmin = min(p[0] for p in pts)
    xmax = max(p[0] for p in pts)
    curve = []
    for x, y in pts:
        frac = (x - xmin) / (xmax - xmin) if xmax > xmin else 0.0
        freq = F_LO * (F_HI / F_LO) ** frac
        curve.append((freq, y_to_db(y)))
    return name, curve, parse_harmonics(html)


def midband_normalize(curve):
    band = [db for f, db in curve if 300.0 <= f <= 3000.0]
    ref = sum(band) / len(band) if band else 0.0
    return [(f, db - ref) for f, db in curve]


def main():
    profiles = []
    if os.path.isdir(MEAS_DIR):
        for fn in sorted(os.listdir(MEAS_DIR)):
            if not fn.lower().endswith(".html"):
                continue
            name, curve, harmonics = parse_report(os.path.join(MEAS_DIR, fn))
            curve = midband_normalize(curve)
            profiles.append((name, curve, harmonics))

    lines = [
        "// GENERATED by tools/gen_audio_interface_profiles.py — do not edit by hand.",
        '#include "audio/AudioInterfaceProfiles.h"',
        "",
        "namespace neuracoust::daw {",
        "namespace {",
        "struct IfaceProfile { const char* name; const double* data; int count; const double* harm; };",
    ]
    for idx, (name, curve, harm) in enumerate(profiles):
        flat = ",".join(f"{f:.4g},{db:.4g}" for f, db in curve)
        lines.append(f"static const double kIfaceProfile{idx}[] = {{{flat}}};")
        hflat = ",".join(f"{c:.6g}" for c in (harm or [0.0] * 6))
        lines.append(f"static const double kIfaceHarm{idx}[6] = {{{hflat}}};  // c2..c7 (linear)")
    lines.append("static const IfaceProfile kIfaceProfiles[] = {")
    for idx, (name, curve, harm) in enumerate(profiles):
        lines.append(f'    {{"{name}", kIfaceProfile{idx}, {len(curve)}, kIfaceHarm{idx}}},')
    lines += [
        "};",
        "} // namespace",
        "",
        "ResponseCurve audioInterfaceProfileCurve(const std::string& catalogName) {",
        "    for (const auto& e : kIfaceProfiles) {",
        "        if (catalogName == e.name) {",
        "            ResponseCurve c; c.reserve(static_cast<size_t>(e.count));",
        "            for (int i = 0; i < e.count; ++i) c.push_back({e.data[i * 2], e.data[i * 2 + 1]});",
        "            return c;",
        "        }",
        "    }",
        "    return {};",
        "}",
        "",
        "std::vector<double> audioInterfaceHarmonics(const std::string& catalogName) {",
        "    for (const auto& e : kIfaceProfiles) {",
        "        if (catalogName == e.name) {",
        "            std::vector<double> h(e.harm, e.harm + 6);",
        "            bool any = false; for (double v : h) any = any || v != 0.0;",
        "            return any ? h : std::vector<double>{};",
        "        }",
        "    }",
        "    return {};",
        "}",
        "",
        "std::vector<std::string> audioInterfaceProfilesWithCurve() {",
        "    std::vector<std::string> names;",
        "    for (const auto& e : kIfaceProfiles) names.emplace_back(e.name);",
        "    return names;",
        "}",
        "",
        "} // namespace neuracoust::daw",
        "",
    ]
    open(OUT_CPP, "w").write("\n".join(lines))
    print(f"wrote {OUT_CPP}: {len(profiles)} interface profile(s): {[p[0] for p in profiles]}")


if __name__ == "__main__":
    main()
