#!/usr/bin/env python3
"""Bake the audio-interface D/A catalog from the research package into a compact C++ catalog
(src/audio/AudioInterfaceCatalog.generated.cpp) plus a metadata JSON resource for the UI.

STRICT (per docs/audio-interface-da-modeling-research/claude_handoff.md):
  • Empty numeric cells stay empty/null — never coerced to 0.
  • Manufacturer specs are UI/validation only; this bakes NO DSP coefficients.
  • "measured" means the row's independent_measurement == 'available' (a real measurement exists),
    which only lights the badge — it does not imply a bundled profile.

Re-run when the catalog CSV changes:
    python3 tools/gen_audio_interface_catalog.py
"""
import csv
import json
import os

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC = os.path.join(ROOT, "docs", "audio-interface-da-modeling-research", "audio_interface_catalog.csv")
OUT_CPP = os.path.join(ROOT, "src", "audio", "AudioInterfaceCatalog.generated.cpp")
OUT_JSON = os.path.join(ROOT, "resources", "audio_interface_catalog.json")

rows = list(csv.DictReader(open(SRC, newline="", encoding="utf-8-sig")))

entries = []   # (display_name, measured)
meta = []
seen = set()
for r in rows:
    brand = (r.get("brand") or "").strip()
    model = (r.get("model") or "").strip()
    if not brand and not model:
        continue
    name = f"{brand} {model}".strip()
    if name in seen:
        continue
    seen.add(name)
    measured = (r.get("independent_measurement") or "").strip() == "available"
    entries.append((name, measured))
    meta.append({
        "name": name,
        "brand": brand,
        "family": (r.get("family") or "").strip(),
        "model": model,
        "era": (r.get("approx_era") or "").strip(),
        "status": (r.get("status") or "").strip(),
        "host": (r.get("host") or "").strip(),
        "maxSampleRateKhz": (r.get("max_sample_rate_khz") or "").strip(),
        "bitDepth": (r.get("bit_depth") or "").strip(),
        "analogOutput": (r.get("analog_output_summary") or "").strip(),
        "dynamicRangeDba": (r.get("da_dynamic_range_dba") or "").strip(),
        "thdnDb": (r.get("da_thdn_db") or "").strip(),
        "maxOutputDbu": (r.get("max_output_dbu") or "").strip(),
        "outputImpedanceOhm": (r.get("output_impedance_ohm") or "").strip(),
        "independentMeasurement": (r.get("independent_measurement") or "").strip(),
        "measurementSource": (r.get("measurement_source") or "").strip(),
        "confidence": (r.get("confidence") or "").strip(),
        "note": (r.get("modeling_note") or "").strip(),
    })

json.dump(meta, open(OUT_JSON, "w"), ensure_ascii=False, indent=1)


def esc(s):
    return s.replace("\\", "\\\\").replace('"', '\\"')


lines = []
lines.append("// GENERATED by tools/gen_audio_interface_catalog.py — do not edit by hand.")
lines.append("// Catalog only: names + whether an independent measurement exists. NO DSP coefficients")
lines.append("// (audio D/A modelling waits for real measured profiles — see the research handoff).")
lines.append('#include "audio/AudioInterfaceCatalog.h"')
lines.append("")
lines.append("#include <unordered_set>")
lines.append("")
lines.append("namespace neuracoust::daw {")
lines.append("")
lines.append("const std::vector<std::string>& audioInterfaceModelCatalog() {")
lines.append("    static const std::vector<std::string> models = {")
lines.append('        "None",')
for name, _measured in entries:
    lines.append(f'        "{esc(name)}",')
lines.append("    };")
lines.append("    return models;")
lines.append("}")
lines.append("")
lines.append("bool audioInterfaceModelMeasured(const std::string& name) {")
lines.append("    static const std::unordered_set<std::string> measured = {")
for name, measured in entries:
    if measured:
        lines.append(f'        "{esc(name)}",')
lines.append("    };")
lines.append("    return measured.count(name) != 0;")
lines.append("}")
lines.append("")
lines.append("} // namespace neuracoust::daw")
lines.append("")

open(OUT_CPP, "w").write("\n".join(lines))
print(f"wrote {OUT_CPP}: {len(entries)} interface models ({sum(1 for _,m in entries if m)} measured)")
print(f"wrote {OUT_JSON}: {len(meta)} metadata records")
