#!/usr/bin/env python3
"""Bake the measured headphone frequency responses from the handoff package into a compact C++
source (src/audio/HeadphoneProfiles.generated.cpp), mirroring gen_speaker_profiles.py, so the
monitor engine can look them up with no runtime CSV parser.

Source: docs/headphone-frequency-response-handoff/curves/<NN_Model_Name>/<first source>.csv
Each curve is `frequency,raw` (relative dB). We take the first source per model, midband-normalize
it (300 Hz–3 kHz mean → 0 dB, matching the speaker dataset convention) and resample onto a compact
log grid. Re-run when the handoff package changes:

    python3 tools/gen_headphone_profiles.py
"""
import csv
import json
import math
import os

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
HANDOFF = os.path.join(ROOT, "docs", "headphone-frequency-response-handoff")
CURVES = os.path.join(HANDOFF, "curves")
OUT = os.path.join(ROOT, "src", "audio", "HeadphoneProfiles.generated.cpp")
META_OUT = os.path.join(ROOT, "resources", "headphone_model_meta.json")

GRID_POINTS = 200
F_LO, F_HI = 20.0, 20000.0


def model_name_from_dir(d):
    # "26_Audio-Technica_ATH-M50x" -> "Audio-Technica ATH-M50x"
    body = d.split("_", 1)[1] if "_" in d else d
    return body.replace("_", " ")


def read_curve(path):
    pts = []
    with open(path, newline="") as f:
        for row in csv.reader(f):
            if len(row) < 2:
                continue
            try:
                hz = float(row[0]); db = float(row[1])
            except ValueError:
                continue  # header / junk
            if hz > 0:
                pts.append((hz, db))
    pts.sort()
    return pts


def interp_db(pts, hz):
    if not pts:
        return 0.0
    if hz <= pts[0][0]:
        return pts[0][1]
    if hz >= pts[-1][0]:
        return pts[-1][1]
    lo, hi = 0, len(pts) - 1
    while hi - lo > 1:
        mid = (lo + hi) // 2
        if pts[mid][0] <= hz:
            lo = mid
        else:
            hi = mid
    (f0, d0), (f1, d1) = pts[lo], pts[hi]
    t = (math.log10(hz) - math.log10(f0)) / (math.log10(f1) - math.log10(f0))
    return d0 + t * (d1 - d0)


def normalize_midband(grid):
    band = [db for hz, db in grid if 300.0 <= hz <= 3000.0]
    mean = sum(band) / len(band) if band else 0.0
    return [(hz, db - mean) for hz, db in grid]


def resample(pts):
    grid = []
    for i in range(GRID_POINTS):
        hz = F_LO * (F_HI / F_LO) ** (i / (GRID_POINTS - 1))
        grid.append((hz, interp_db(pts, hz)))
    return normalize_midband(grid)


# Provenance from measurements.jsonl, keyed by the relative CSV path.
meta_by_csv = {}
mjl = os.path.join(HANDOFF, "measurements.jsonl")
if os.path.exists(mjl):
    for line in open(mjl):
        line = line.strip()
        if not line:
            continue
        try:
            rec = json.loads(line)
        except ValueError:
            continue
        meta_by_csv[rec.get("relative_csv", "")] = rec

# Catalog status (all measurement sources, status), keyed by model name.
status_by_name = {}
csv_status = os.path.join(HANDOFF, "catalog_status.csv")
if os.path.exists(csv_status):
    with open(csv_status, newline="", encoding="utf-8-sig") as f:
        for row in csv.DictReader(f):
            status_by_name[row.get("catalog_model", "")] = row


def form_factor(url):
    for kind, label in (("/over-ear/", "오버이어"), ("/on-ear/", "온이어"),
                        ("/in-ear/", "인이어"), ("/earbud/", "이어버드")):
        if url and kind in url:
            return label
    return ""


entries = []
meta = []
for d in sorted(os.listdir(CURVES)):
    full = os.path.join(CURVES, d)
    if not os.path.isdir(full):
        continue
    csvs = sorted(f for f in os.listdir(full) if f.lower().endswith(".csv"))
    if not csvs:
        continue
    pts = read_curve(os.path.join(full, csvs[0]))
    if len(pts) < 8:
        continue
    name = model_name_from_dir(d)
    entries.append((name, resample(pts), csvs[0]))
    rec = meta_by_csv.get(f"curves/{d}/{csvs[0]}", {})
    st = status_by_name.get(name, {})
    all_sources = [s.strip() for s in (st.get("measurement_sources") or "").split(";") if s.strip()]
    meta.append({
        "name": name,
        "source": rec.get("measurement_source", ""),
        "sourceUrl": rec.get("github_file_url", ""),
        "formFactor": form_factor(rec.get("github_file_url", "")),
        "sourceCount": sum(1 for f in csvs),
        "pointCount": rec.get("point_count", len(pts)),
        "status": st.get("status", ""),
        "sources": all_sources,
    })

json.dump(meta, open(META_OUT, "w"), ensure_ascii=False, indent=1)
print(f"wrote {META_OUT}: {len(meta)} headphone metadata records")


def esc(s):
    return s.replace("\\", "\\\\").replace('"', '\\"')


lines = []
lines.append("// GENERATED by tools/gen_headphone_profiles.py — do not edit by hand.")
lines.append('#include "audio/HeadphoneProfiles.h"')
lines.append("")
lines.append("namespace neuracoust::daw {")
lines.append("namespace {")
lines.append("struct ProfileEntry { const char* name; const double* data; int count; };")
for i, (name, curve, _src) in enumerate(entries):
    nums = ",".join(f"{hz:g},{db:g}" for hz, db in curve)
    lines.append(f"static const double kHpProfile{i}[] = {{{nums}}};")
lines.append("static const ProfileEntry kHpProfiles[] = {")
for i, (name, curve, _src) in enumerate(entries):
    lines.append(f'    {{"{esc(name)}", kHpProfile{i}, {len(curve)}}},')
lines.append("};")
lines.append("} // namespace")
lines.append("")
lines.append("ResponseCurve headphoneProfileCurve(const std::string& catalogName) {")
lines.append("    for (const auto& e : kHpProfiles) {")
lines.append("        if (catalogName == e.name) {")
lines.append("            ResponseCurve c; c.reserve(static_cast<size_t>(e.count));")
lines.append("            for (int i = 0; i < e.count; ++i) c.push_back({e.data[i * 2], e.data[i * 2 + 1]});")
lines.append("            return c;")
lines.append("        }")
lines.append("    }")
lines.append("    return {};")
lines.append("}")
lines.append("")
lines.append("std::vector<std::string> headphoneProfilesWithCurve() {")
lines.append("    std::vector<std::string> names;")
lines.append("    names.reserve(sizeof(kHpProfiles) / sizeof(kHpProfiles[0]));")
lines.append("    for (const auto& e : kHpProfiles) names.emplace_back(e.name);")
lines.append("    return names;")
lines.append("}")
lines.append("")
lines.append("} // namespace neuracoust::daw")
lines.append("")

open(OUT, "w").write("\n".join(lines))
print(f"wrote {OUT}: {len(entries)} measured headphone curves")
